version: '3.8'

services:
  flarenet-ml-backend:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - ./models:/app/models
      - ./configs:/app/configs
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
    networks:
      - flarenet-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: flarenet
      POSTGRES_USER: flarenet_user
      POSTGRES_PASSWORD: flarenet_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - flarenet-network
    restart: unless-stopped

networks:
  flarenet-network:
    driver: bridge

volumes:
  postgres_data: