spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:flarenet}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USER:flarenet}
    password: ${DB_PASS:flarenet}
    driver-class-name: com.mysql.cj.jdbc.Driver
