spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:flarenet}
    username: ${DB_USER:flarenet}
    password: ${DB_PASS:flarenet}
    driver-class-name: org.postgresql.Driver
